# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fund.proto import fund_service_pb2 as fund__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fund_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FundServiceStub(object):
    """── Service ────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentState = channel.unary_unary(
                '/fund.FundService/GetCurrentState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.FundState.FromString,
                _registered_method=True)
        self.GetWeeklyNAVHistory = channel.unary_stream(
                '/fund.FundService/GetWeeklyNAVHistory',
                request_serializer=fund__service__pb2.TimeRange.SerializeToString,
                response_deserializer=fund__service__pb2.WeeklyNAVRecord.FromString,
                _registered_method=True)
        self.GetMemberPosition = channel.unary_unary(
                '/fund.FundService/GetMemberPosition',
                request_serializer=fund__service__pb2.MemberId.SerializeToString,
                response_deserializer=fund__service__pb2.MemberPosition.FromString,
                _registered_method=True)
        self.GetMemberWhatIf = channel.unary_unary(
                '/fund.FundService/GetMemberWhatIf',
                request_serializer=fund__service__pb2.WhatIfRequest.SerializeToString,
                response_deserializer=fund__service__pb2.WhatIfResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/fund.FundService/GetPositions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.Positions.FromString,
                _registered_method=True)
        self.GetUniverse = channel.unary_unary(
                '/fund.FundService/GetUniverse',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.InvestmentUniverseMsg.FromString,
                _registered_method=True)
        self.GetBenchmarkComparison = channel.unary_unary(
                '/fund.FundService/GetBenchmarkComparison',
                request_serializer=fund__service__pb2.TimeRange.SerializeToString,
                response_deserializer=fund__service__pb2.BenchmarkData.FromString,
                _registered_method=True)
        self.GetAlternativeUniverses = channel.unary_unary(
                '/fund.FundService/GetAlternativeUniverses',
                request_serializer=fund__service__pb2.TimeRange.SerializeToString,
                response_deserializer=fund__service__pb2.UniverseComparison.FromString,
                _registered_method=True)
        self.GetThermoMetrics = channel.unary_unary(
                '/fund.FundService/GetThermoMetrics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.ThermoSnapshot.FromString,
                _registered_method=True)
        self.StreamThermoMetrics = channel.unary_stream(
                '/fund.FundService/StreamThermoMetrics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.ThermoSnapshot.FromString,
                _registered_method=True)
        self.GetBeliefNarrative = channel.unary_unary(
                '/fund.FundService/GetBeliefNarrative',
                request_serializer=fund__service__pb2.TimeRange.SerializeToString,
                response_deserializer=fund__service__pb2.BeliefReport.FromString,
                _registered_method=True)
        self.GetDecisionLog = channel.unary_stream(
                '/fund.FundService/GetDecisionLog',
                request_serializer=fund__service__pb2.TimeRange.SerializeToString,
                response_deserializer=fund__service__pb2.Decision.FromString,
                _registered_method=True)
        self.GetDailyJournal = channel.unary_unary(
                '/fund.FundService/GetDailyJournal',
                request_serializer=fund__service__pb2.JournalDate.SerializeToString,
                response_deserializer=fund__service__pb2.DailyJournalMsg.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/fund.FundService/StreamEvents',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.FundEvent.FromString,
                _registered_method=True)
        self.GetEngineStatus = channel.unary_unary(
                '/fund.FundService/GetEngineStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fund__service__pb2.EngineStatus.FromString,
                _registered_method=True)


class FundServiceServicer(object):
    """── Service ────────────────────────────────────────────────

    """

    def GetCurrentState(self, request, context):
        """Fund state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeeklyNAVHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberPosition(self, request, context):
        """Member
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberWhatIf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Positions & universe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUniverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBenchmarkComparison(self, request, context):
        """Benchmarks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlternativeUniverses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThermoMetrics(self, request, context):
        """Thermodynamic metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamThermoMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBeliefNarrative(self, request, context):
        """Belief narratives
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecisionLog(self, request, context):
        """Decisions / journal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDailyJournal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Events & notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineStatus(self, request, context):
        """Heartbeat (cloud polls or Mac pushes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.FundState.SerializeToString,
            ),
            'GetWeeklyNAVHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetWeeklyNAVHistory,
                    request_deserializer=fund__service__pb2.TimeRange.FromString,
                    response_serializer=fund__service__pb2.WeeklyNAVRecord.SerializeToString,
            ),
            'GetMemberPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberPosition,
                    request_deserializer=fund__service__pb2.MemberId.FromString,
                    response_serializer=fund__service__pb2.MemberPosition.SerializeToString,
            ),
            'GetMemberWhatIf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberWhatIf,
                    request_deserializer=fund__service__pb2.WhatIfRequest.FromString,
                    response_serializer=fund__service__pb2.WhatIfResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.Positions.SerializeToString,
            ),
            'GetUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUniverse,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.InvestmentUniverseMsg.SerializeToString,
            ),
            'GetBenchmarkComparison': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBenchmarkComparison,
                    request_deserializer=fund__service__pb2.TimeRange.FromString,
                    response_serializer=fund__service__pb2.BenchmarkData.SerializeToString,
            ),
            'GetAlternativeUniverses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlternativeUniverses,
                    request_deserializer=fund__service__pb2.TimeRange.FromString,
                    response_serializer=fund__service__pb2.UniverseComparison.SerializeToString,
            ),
            'GetThermoMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThermoMetrics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.ThermoSnapshot.SerializeToString,
            ),
            'StreamThermoMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamThermoMetrics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.ThermoSnapshot.SerializeToString,
            ),
            'GetBeliefNarrative': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeliefNarrative,
                    request_deserializer=fund__service__pb2.TimeRange.FromString,
                    response_serializer=fund__service__pb2.BeliefReport.SerializeToString,
            ),
            'GetDecisionLog': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDecisionLog,
                    request_deserializer=fund__service__pb2.TimeRange.FromString,
                    response_serializer=fund__service__pb2.Decision.SerializeToString,
            ),
            'GetDailyJournal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyJournal,
                    request_deserializer=fund__service__pb2.JournalDate.FromString,
                    response_serializer=fund__service__pb2.DailyJournalMsg.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.FundEvent.SerializeToString,
            ),
            'GetEngineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fund__service__pb2.EngineStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fund.FundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fund.FundService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FundService(object):
    """── Service ────────────────────────────────────────────────

    """

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetCurrentState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.FundState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeeklyNAVHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fund.FundService/GetWeeklyNAVHistory',
            fund__service__pb2.TimeRange.SerializeToString,
            fund__service__pb2.WeeklyNAVRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetMemberPosition',
            fund__service__pb2.MemberId.SerializeToString,
            fund__service__pb2.MemberPosition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberWhatIf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetMemberWhatIf',
            fund__service__pb2.WhatIfRequest.SerializeToString,
            fund__service__pb2.WhatIfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetPositions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.Positions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetUniverse',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.InvestmentUniverseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBenchmarkComparison(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetBenchmarkComparison',
            fund__service__pb2.TimeRange.SerializeToString,
            fund__service__pb2.BenchmarkData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlternativeUniverses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetAlternativeUniverses',
            fund__service__pb2.TimeRange.SerializeToString,
            fund__service__pb2.UniverseComparison.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThermoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetThermoMetrics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.ThermoSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamThermoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fund.FundService/StreamThermoMetrics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.ThermoSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBeliefNarrative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetBeliefNarrative',
            fund__service__pb2.TimeRange.SerializeToString,
            fund__service__pb2.BeliefReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecisionLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fund.FundService/GetDecisionLog',
            fund__service__pb2.TimeRange.SerializeToString,
            fund__service__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDailyJournal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetDailyJournal',
            fund__service__pb2.JournalDate.SerializeToString,
            fund__service__pb2.DailyJournalMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fund.FundService/StreamEvents',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.FundEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fund.FundService/GetEngineStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fund__service__pb2.EngineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
